'use client';

import { Fragment } from 'react';
import type { AnswerData } from '@/types/search';

interface AnswerBoxProps {
  answer: AnswerData | null;
  isLoading: boolean;
}

/** Render answer text, turning `[n]` markers into links to the nth source. */
function AnswerText({ answer }: { answer: AnswerData }) {
  const parts = answer.answer.split(/(\[\d+\])/g);
  return (
    <p className="text-[15px] leading-relaxed">
      {parts.map((part, i) => {
        const m = part.match(/^\[(\d+)\]$/);
        if (m) {
          const n = Number(m[1]);
          const source = answer.sources.find((s) => s.n === n);
          if (source) {
            return (
              <a
                key={i}
                href={source.url}
                target="_blank"
                rel="noopener noreferrer"
                title={source.title ?? source.url}
                className="mx-0.5 inline-flex h-4 min-w-4 items-center justify-center rounded bg-blue-600/10 px-1 align-super text-[10px] font-semibold text-blue-700 no-underline hover:bg-blue-600/20 dark:bg-blue-400/15 dark:text-blue-300"
              >
                {n}
              </a>
            );
          }
        }
        return <Fragment key={i}>{part}</Fragment>;
      })}
    </p>
  );
}

export function AnswerBox({ answer, isLoading }: AnswerBoxProps) {
  if (isLoading) {
    return (
      <div className="mt-6 animate-pulse rounded-2xl border border-black/5 bg-black/[0.02] p-5 dark:border-white/10 dark:bg-white/[0.03]">
        <div className="mb-3 h-3 w-24 rounded bg-black/10 dark:bg-white/10" />
        <div className="space-y-2">
          <div className="h-3 w-full rounded bg-black/5 dark:bg-white/5" />
          <div className="h-3 w-11/12 rounded bg-black/5 dark:bg-white/5" />
          <div className="h-3 w-4/5 rounded bg-black/5 dark:bg-white/5" />
        </div>
      </div>
    );
  }

  if (!answer || answer.sources.length === 0) return null;

  const isLlm = answer.generator === 'llm';

  return (
    <section className="mt-6 rounded-2xl border border-blue-600/15 bg-gradient-to-b from-blue-600/[0.06] to-transparent p-5 dark:border-blue-400/15 dark:from-blue-400/[0.07]">
      <div className="mb-3 flex items-center gap-2">
        <span className="inline-flex items-center gap-1.5 text-sm font-semibold">
          <svg viewBox="0 0 24 24" className="h-4 w-4 text-blue-600 dark:text-blue-400" fill="currentColor" aria-hidden="true">
            <path d="M11 2 8.5 8.5 2 11l6.5 2.5L11 20l2.5-6.5L20 11l-6.5-2.5L11 2Z" />
          </svg>
          AI Answer
        </span>
        <span
          className="rounded-full border border-black/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide opacity-60 dark:border-white/15"
          title={isLlm ? `Generated by ${answer.model}` : 'Extractive summary (no LLM key configured)'}
        >
          {isLlm ? answer.model : 'extractive'}
        </span>
      </div>

      <AnswerText answer={answer} />

      <p className="mt-3 text-xs opacity-50">
        AI-generated from the indexed sources below — verify important details.
      </p>

      <div className="mt-4 border-t border-black/5 pt-3 dark:border-white/10">
        <p className="mb-2 text-xs font-medium uppercase tracking-wide opacity-50">Sources</p>
        <ol className="space-y-1.5">
          {answer.sources.map((s) => (
            <li key={s.n} className="flex gap-2 text-sm">
              <span className="mt-0.5 flex h-4 min-w-4 items-center justify-center rounded bg-black/5 px-1 text-[10px] font-semibold opacity-60 dark:bg-white/10">
                {s.n}
              </span>
              <a
                href={s.url}
                target="_blank"
                rel="noopener noreferrer"
                className="truncate text-blue-700 hover:underline dark:text-blue-400"
                title={s.url}
              >
                {s.title || s.url}
              </a>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}
